[package]
name = "libwaysip"
description = "lib and tool provide function like slurp"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
tempfile = "3.8.1"
wayland-client = { version = "0.31.1" }
wayland-cursor = "0.31.0"

wayland-protocols = { version = "0.31.0", default-features = false, features = [
	"unstable",
	"client",
] }

wayland-protocols-wlr = { version = "0.2.0", default-features = false, features = [
	"client",
] }

cairo-rs = "0.18.3"
pango = "0.18.3"
pangocairo = "0.18.0"

memmap2 = "0.9.0"
thiserror = "1.0.50"
