[package]
name = "waysip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.8.1"
wayland-client = { version = "0.31.1" }
wayland-cursor = "0.31.0"

wayland-protocols = { version = "0.31.0", default-features = false, features = [
	"unstable",
	"client",
] }

wayland-protocols-wlr = { version = "0.2.0", default-features = false, features = [
	"client",
] }

cairo-rs = "0.18.2"
pango = "0.18.0"
pangocairo = "0.18.0"

memmap2 = "0.9.0"
thiserror = "1.0.50"
