[workspace]
resolver = "2"
members = ["./waysip", "./libwaysip"]

[workspace.package]
authors = ["Decodertalkers <aakari@tutanota.com>"]
edition = "2021"
version = "0.1.0"
license = "MIT"
description = "lib provide function like slurp"
repository = "https://github.com/waycrate/waysip"
keywords = ["wayland", "wlroots", "slurp"]

[workspace.dependencies]
libwaysip = { version = "0.1.0", path = "./libwaysip" }
