name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt install -y libpango1.0-dev libcairo2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
